# This workflow labels stale PRs after 30 days of inactivity, then closes them a week later if not updated.
# For more information, see: https://github.com/actions/stale

name: Mark Stale Issues 2

on:
  # Enable manual run from the Actions tab so workflow can be run at any time
  workflow_dispatch:
  # Scheduled to run at 12:00 on every Monday
  schedule:
    - cron: "0 0 * * MON"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # mark stale after 30 days of no activity
          days-before-pr-stale: 1
          # close pr after 1 week no updates after stale warning
          days-before-pr-close: 2
          # disabling removing stale label because all activity counts as updates.
          remove-pr-stale-when-updated: false
          stale-pr-label: "stale"
          stale-pr-message: "As per Chayn policy, after 30 days of inactivity, we will close this PR."
          close-pr-message: 'This PR has been closed due to inactivity.'
